name: Build and deploy Python app to Azure Web App

on:
  push:
    branches:
      - main  # o master, según tu repositorio

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python version
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Create and start virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Make startup script executable
      run: |
        chmod +x startup.sh
        
    - name: Create necessary directories
      run: |
        mkdir -p .streamlit
        mkdir -p data/vector_stores

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'DistribunaIA-APP'  # Reemplaza con el nombre de tu app
        slot-name: 'production'
        publish-profile: ${{ secrets.AZUREWEBAPP_PUBLISHPROFILE }}
