[theme]
primaryColor = "#499f70"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#333333"
font = "sans serif"

[server]
port = 8000
headless = true
enableCORS = false
enableXsrfProtection = true